### ISSUE TITLE
create an internal train/test split to assess different prediction approaches

### ISSUE THREAD

**Issue by kaichop** [WGLab/Project_Belka#1]
take 80% of the train.csv and create a new newtrain and take 20% and create a newtest file, so that we can evaluate different approaches on known results. This should be done in a random fashion rather than taking the first 80% lines.

**Comment by umahsn** [comment]
Completed.

**Comment by umahsn** [comment]
Located here: `/mnt/isilon/wang_lab/shared/Belka/raw_data`

**Comment by Euchiz** [comment]
I generated the parquet version of the splits to the same location.
