### ISSUE TITLE
evaluate how to make a submission and get a score

### ISSUE THREAD

**Issue by kaichop** [WGLab/Project_Belka#6]
Likely use a fake account to make submission so we know how the process works.

**Comment by wangwpi** [comment]
The website says each member could submit 5 entries per day, so I will try to submit the result using the Leash Tutorial random forest model.
```
**Submission Limits**
You may submit a maximum of 5 entries per day. 
You may select up to 2 final submissions for judging.
```

**Comment by wangwpi** [comment]
To submit the prediction, simply predict all `test.csv` and generate a csv file following the format of `sample_submission.csv`. After getting the submission.csv file, upload the file into submission page https://www.kaggle.com/competitions/leash-BELKA/submissions.
After submission a **public score** will be given, the random forest using ECFP encode got 0.263 score.
![image](https://github.com/WGLab/Project_Belka/assets/129898246/92fdeb36-19a4-47bf-afa6-5b919299eb7b)
