### ISSUE TITLE
Term merge dealine coming soon

### ISSUE THREAD

**Issue by wangwpi** [WGLab/Project_Belka#8]
As the deadline of team merge is soon coming, we should merge our team before July 1. You will need to join the compitition first. So everyone **please join the kaggle challenge and send me your username and team name (under "Team" tab in the challange page)** so i could invite you to the team. 

- [ ] Join the kaggle challange and accept the compitition rules. https://www.kaggle.com/competitions/leash-BELKA/overview
- [ ] send me your username so i could invite you to the team.
- [ ] accept the team invitition.

**Comment by kaichop** [comment]
my username is kaichop

**Comment by wangwpi** [comment]
team merge completed.
